
output "cluster_endpoint" {
    value = module.eks.cluster_endpoint
    description = "Endpoint for EKS control plane."
}

output "kubectl_config" {
    value = module.eks.kubeconfig
    description = "kubectl config as generated by the moudle."
}

output "config_map_aws_auth" {
    value = module.eks.config_map_aws_auth
    description = "A kubernetes configuration to authenticate to this EKS cluster."
}

output "nat_gateway_id" {
    value = aws_nat_gateway.eks_test_ngw.id
}