# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
data:
  mapAccounts: 
    []
  mapRoles:
    - rolearn: arn:aws:iam::525759056232:role/eks-terraform-jong20210521003008565600000008
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes

    - rolearn: arn:aws:iam::525759056232:role/hello-iam-role
      username: jonghe
      groups:
        - devops

  mapUsers: 
    []
    #    - "userarn": "arn:aws:iam::525759056232:user/terraform-jong"
    #      "username": "terraform-jong"
    #      "groups":
    #      - "system:masters"
kind: ConfigMap
metadata:
#   creationTimestamp: "2021-05-21T00:30:14Z"
  name: aws-auth
  namespace: kube-system
#   resourceVersion: "32448"
#   selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
#   uid: df69bc79-7243-470d-afcd-9173185f61ac