apiVersion: v1
data:
  mapAccounts: |
    []
  mapRoles: |
    - rolearn: arn:aws:iam::525759056232:role/eks-terraform-jong20210523033219435300000008
      username: system:node:{{EC2PrivateDNSName}}
      groups:  
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::525759056232:role/hello-iam-role
      username: jongjong
      groups:
        - dev
#         - system:masters        
#        - system:bootstrappers
#        - system:nodes
       
  mapUsers: |
    - "userarn": "arn:aws:iam::525759056232:user/terraform-jong"
      "username": "jonghe"
      "groups":
      - "devops"
kind: ConfigMap
metadata:
  # creationTimestamp: "2021-05-23T03:32:24Z"
  name: aws-auth
  namespace: kube-system
  # resourceVersion: "34947"
  # selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  # uid: f39662fc-7435-40e4-83f5-4f5fbae335a4